// packages/react-async-cache/example/src/Counter.js
import React from 'react';
import { useAsyncCacheWatch } from 'react-async-cache';
import { api } from './mockapi';

export const Counter = () => {
    const { call, response } = useAsyncCacheWatch(api, '/counter');

    React.useEffect(() => {
        // call api to get current counter value and cache it
        // it will avoid unecessary simultanous call
        call();
    });
    return (
        <div>
            Counter: { response || 'loading...'}
        </div>
    );
}

// packages/vue-async-cache/example/src/components/Counter.vue
<template>
  <div class="counter">
    <p>Counter: {{count}}</p>
  </div>
</template>

<script lang="ts">
import {
  Component,
  Vue,
} from "vue-property-decorator";
import { api } from "../mockapi";
import { useAsyncCacheWatch } from "vue-async-cache";

@Component
export default class Counter extends Vue {
  private cacheWatch = useAsyncCacheWatch(() => api("/counter"));

  get count() {
    return this.cacheWatch.getResponse();
  }

  async mounted() {
    this.cacheWatch.call();
  }
}
</script>
