// packages/vue-async-cache/example/src/components/ErrorExample.vue
<template>
  <div>
    <!-- <p>store {{store}}</p> -->
    <p class="error"><b>Some error handling example:</b> {{error}} </p>
  </div>
</template>

<script lang="ts">
import {
  Component,
  Vue,
} from "vue-property-decorator";
import { api } from "../mockapi";
import { asyncCache, useAsyncCacheWatch } from "vue-async-cache";

@Component
export default class ErrorExample extends Vue {
  private cacheWatch = useAsyncCacheWatch(api, "/no-route");

  get error() {
    return this.cacheWatch.getError();
  }

  // data() {
  //   return {
  //     store: asyncCache.state,
  //   };
  // }

  mounted() {
    this.cacheWatch.call();
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
.error {
  color: red;
}
</style>

// packages/react-async-cache/example/src/ErrorExample.js
import React from 'react';
import { useAsyncCacheWatch } from 'react-async-cache';
import { api } from './mockapi';

const errorStyle = {
  color: 'red',
}

export const ErrorExample = () => {
  const { call, response, error } = useAsyncCacheWatch(() => api('/no-route'));
  React.useEffect(() => {
    call();
  });
  return (
    <div style={errorStyle}>
      {!response && !error && <p>loading...</p>}
      {error && <p><b>Some error handling example:</b> {error} </p>}
    </div>
  );
}
